### ISSUE TITLE
6 ran away because it was afraid of 7

### ISSUE THREAD

**Issue by mkalvas** [bartlettc22/lIllI#2]
As a l33t haX0r, I noticed a binary pattern in the matrix but also that 6 (`llIIl`) is nowhere to be found. Instead it went from 5 (`lllIlI`) to 7 (`lllIII`).

## Expected Behavior
Binary counting pattern is sequentially incremented by 1

## Current Behavior
Binary counting pattern is sequentially incremented by 1 but has an anomaly. When 5 is incremented, it actually increments by 2 which throws off the rest of the pattern that follows.

## Possible Solution
Refactor the entire code base so that the correct pattern is observed and the high code standards for this project are upheld.

## Steps to Reproduce
1. Learn binary
1. Look at source code
1. Count on your fingers as you go along (note: you may require toes depending on how much radioactive waste you played with as a child.)
1. Realize the source code is a dirty, dirty liar

## Context (Environment)
I was just trying to mind my own business and enjoy myself on reddit when I saw this awesome program. I immediately realized that it's a unix system and yelled out loud to myself "I know this!" I started to analyze the code so that I could hope to learn how to put even a fraction of its elegance into my own coding projects, but that's when disaster struck and I saw this massive flaw in the system.

## Possible Implementation
It'll be tough but I think we could really dive in and re-write code sections 6-15 in order to fix this once and for all.

**Comment by bartlettc22** [comment]
You're absolutely right - there is no excuse.  Please see PR #3 and let me know if this solves your problem.

**Comment by bartlettc22** [comment]
I also noticed we were starting at 1 instead of 0 so I fixed that as well...
